import { CalorieUnit, MealType, Unit } from './models/enums';

const STARTING_DATA = {
  startingIngredients: [
    { name: 'Tyúktojás (M)', calorie: 76, calorieUnit: CalorieUnit.piece, unit: Unit.piece },
    { name: 'Burgonya', calorie: 77, calorieUnit: CalorieUnit.kcalg, unit: Unit.g },
    { name: 'Basmati rizs (száraz)', calorie: 360, calorieUnit: CalorieUnit.kcalg, unit: Unit.g },
    { name: 'Csirkemell', calorie: 120, calorieUnit: CalorieUnit.kcalg, unit: Unit.g },
    { name: 'Sertéskaraj (hosszú karaj)', calorie: 155, calorieUnit: CalorieUnit.kcalg, unit: Unit.g },
    { name: 'SPAR UHT tej 2,8%-os', calorie: 56, calorieUnit: CalorieUnit.kcalml, unit: Unit.ml },
    { name: 'Durumtészta (száraz)', calorie: 360, calorieUnit: CalorieUnit.kcalg , unit: Unit.g},
    { name: 'Olívaolaj', calorie: 813, calorieUnit: CalorieUnit.kcalml, unit: Unit.ml },
    { name: 'Paradicsom (közepes)', calorie: 22, calorieUnit: CalorieUnit.piece, unit: Unit.piece },
    { name: 'Alma (150g)', calorie: 78, calorieUnit: CalorieUnit.piece, unit: Unit.piece },
    { name: 'Körte (közepes)', calorie: 101, calorieUnit: CalorieUnit.piece, unit: Unit.piece },
    { name: 'Joghurt', calorie: 57, calorieUnit: CalorieUnit.kcalg, unit: Unit.g },
    { name: 'Lilahagyma (közepes)', calorie: 46, calorieUnit: CalorieUnit.piece, unit: Unit.piece },
    { name: 'Vaj', calorie: 742, calorieUnit: CalorieUnit.kcalg, unit: Unit.g },
    { name: 'Trappista sajt', calorie: 352, calorieUnit: CalorieUnit.kcalg, unit: Unit.g },
    { name: 'Sertéssonka', calorie: 147, calorieUnit: CalorieUnit.kcalg, unit: Unit.g },
    { name: 'Teljeskiörlésű kenyér szelet (32g)', calorie: 80, calorieUnit: CalorieUnit.piece, unit: Unit.piece},
    { name: 'Só', calorie: 0, calorieUnit: CalorieUnit.kcalg, unit: Unit.g },
    { name: 'Bors (fűszer)', calorie: 251, calorieUnit: CalorieUnit.kcalg , unit: Unit.g},
    { name: 'Piros paprika (fűszer)', calorie: 282, calorieUnit: CalorieUnit.kcalg, unit: Unit.g },
    { name: 'Víz', calorie: 0, calorieUnit: CalorieUnit.kcalml, unit: Unit.ml },
  ],
  startingMeals: [
    {
      name: 'Sonkás sajtos szendvics (2db)',
      calorie: 778,
      MealType: [MealType.breakfest, MealType.dinner, MealType.other],
      ingredients: [
        {
          name: 'Teljeskiörlésű kenyér szelet (32g)',
          amount: 4,
          unit: Unit.piece,
          calorie: 320,
          calorieUnit: CalorieUnit.piece,
        },
        {
          name: 'Sertéssonka',
          amount: 20,
          unit: Unit.g,
          calorie: 30,
          calorieUnit: CalorieUnit.kcalg,
        },
        {
          name: 'Trappista sajt',
          amount: 40,
          unit: Unit.g,
          calorie: 140,
          calorieUnit: CalorieUnit.kcalg,
        },
        {
          name: 'Vaj',
          amount: 20,
          unit: Unit.g,
          calorie: 148,
          calorieUnit: CalorieUnit.kcalg,
        },
      ],
    },
    {
      name: 'Párolt csirkemell rizzsel',
      calorie: 512,
      MealType: [MealType.lunch],
      ingredients: [
        {
          name: 'Só',
          amount: 3,
          unit: Unit.g,
          calorie: 0,
          calorieUnit: CalorieUnit.kcalg,
        },
        {
          name: 'Csirkemell',
          amount: 20,
          unit: Unit.dkg,
          calorie: 240,
          calorieUnit: CalorieUnit.kcalg,
        },
        {
          name: 'Bors (fűszer)',
          amount: 1,
          unit: Unit.g,
          calorie: 3,
          calorieUnit: CalorieUnit.kcalg,
        },
        {
          name: 'Olívaolaj',
          amount: 11,
          unit: Unit.ml,
          calorie: 89,
          calorieUnit: CalorieUnit.kcalml,
        },
        ,
        {
          name: 'Basmati rizs (száraz)',
          amount: 5,
          unit: Unit.dkg,
          calorie: 180,
          calorieUnit: CalorieUnit.kcalg,
        },
        ,
        {
          name: 'Víz',
          amount: 1,
          unit: Unit.dl,
          calorie: 0,
          calorieUnit: CalorieUnit.kcalml,
        },
      ],
    },
    {
      name: 'Párolt sertéskaraj sültkrumplival',
      calorie: 596,
      MealType: [MealType.lunch],
      ingredients: [
        {
          name: 'Só',
          amount: 3,
          unit: Unit.g,
          calorie: 0,
          calorieUnit: CalorieUnit.kcalg,
        },
        {
          name: 'Sertéskaraj (hosszú karaj)',
          amount: 20,
          unit: Unit.dkg,
          calorie: 310,
          calorieUnit: CalorieUnit.kcalg,
        },
        {
          name: 'Olívaolaj',
          amount: 11,
          unit: Unit.ml,
          calorie: 89,
          calorieUnit: CalorieUnit.kcalml,
        },
        ,
        {
          name: 'Burgonya',
          amount: 20,
          unit: Unit.dkg,
          calorie: 174,
          calorieUnit: CalorieUnit.kcalg,
        },
        ,
        {
          name: 'Lilahagyma (közepes)',
          amount: 0.5,
          unit: Unit.piece,
          calorie: 23,
          calorieUnit: CalorieUnit.piece,
        },
      ],
    },
    {
      name: 'Egy pohár joghurt',
      calorie: 114,
      MealType: [MealType.breakfest, MealType.other],
      ingredients: [
        {
          name: 'Joghurt',
          amount: 200,
          unit: Unit.g,
          calorie: 114,
          calorieUnit: CalorieUnit.kcalg,
        },
      ],
    },
    {
      name: 'Tojásos rántotta',
      calorie: 556,
      MealType: [MealType.breakfest, MealType.dinner],
      ingredients: [
        {
          name: 'Teljeskiörlésű kenyér szelet (32g)',
          amount: 2,
          unit: Unit.piece,
          calorie: 160,
          calorieUnit: CalorieUnit.piece,
        },
        {
          name: 'Tyúktojás (M)',
          amount: 4,
          unit: Unit.piece,
          calorie: 304,
          calorieUnit: CalorieUnit.piece,
        },
        {
          name: 'Olívaolaj',
          amount: 11,
          unit: Unit.ml,
          calorie: 89,
          calorieUnit: CalorieUnit.kcalml,
        },
        {
          name: 'Só',
          amount: 1,
          unit: Unit.g,
          calorie: 0,
          calorieUnit: CalorieUnit.kcalg,
        },
        {
          name: 'Piros paprika (fűszer)',
          amount: 1,
          unit: Unit.g,
          calorie: 3,
          calorieUnit: CalorieUnit.kcalg,
        },
      ],
    },
    {
      name: 'Tükör tojás',
      calorie: 553,
      MealType: [MealType.breakfest, MealType.dinner],
      ingredients: [
        {
          name: 'Teljeskiörlésű kenyér szelet (32g)',
          amount: 2,
          unit: Unit.piece,
          calorie: 160,
          calorieUnit: CalorieUnit.piece,
        },
        {
          name: 'Tyúktojás (M)',
          amount: 4,
          unit: Unit.piece,
          calorie: 304,
          calorieUnit: CalorieUnit.piece,
        },
        {
          name: 'Olívaolaj',
          amount: 11,
          unit: Unit.ml,
          calorie: 89,
          calorieUnit: CalorieUnit.kcalml,
        },
        {
          name: 'Só',
          amount: 1,
          unit: Unit.g,
          calorie: 0,
          calorieUnit: CalorieUnit.kcalg,
        },
      ],
    },
    {
      name: 'Két alma',
      calorie: 156,
      MealType: [MealType.other],
      ingredients: [
        {
          name: 'Alma (150g)',
          amount: 2,
          unit: Unit.piece,
          calorie: 156,
          calorieUnit: CalorieUnit.piece,
        },
      ],
    },
    {
      name: 'Két körte',
      calorie: 202,
      MealType: [MealType.other],
      ingredients: [
        {
          name: 'Körte (közepes)',
          amount: 2,
          unit: Unit.piece,
          calorie: 202,
          calorieUnit: CalorieUnit.piece,
        },
      ],
    },
  ],
};

export default STARTING_DATA;
